### ISSUE TITLE
Enhance intuitivity of "Banca este proyecto" button (UI/UX)

### ISSUE THREAD

**Issue by facundomedica** [virtuagora/virtuagora-core#7]
On desktop the UX is ok (can be improved) but on mobile is very difficult to know that the "muscle badge" is a button (there's no mouse-over, so the tooltip doesn't show up).

An animation/arrow/indicator should be added and shown as soon as the user enters the site. For example: The bounce that the button makes when clicked should be made a couple of seconds after the users enters the site and/or be executed every 5/10 seconds. Also showing the tooltip "Clic aqui para bancar este proyecto" by default should help.

I would make a pull request myself but UI/UX is not my specialty.

Edit: This issue should be addressed ASAP because the Ingenia voting is live

**Comment by guillecro** [comment]
@facundomedica THE FUCK IS THIS

**Comment by facundomedica** [comment]
@guillecro it's a suggestion of enhancement. Parentesis de ingles: escribi en ingles porque vi que los demas issues estan en ingles y ademas no tengo tilde en este teclado. Sucede que somos varias personas de entre 17 y 25 anios y a todos nos parecio complicado el tema de votar. Lo que menos queremos es que la gente se frustre y no vote. De todas formas vamos a hacer una campania con un mini tutorial en video. Saludos!

**Comment by guillecro** [comment]
Haha to be honest i am coming back home and i want to make some notes on this, but you are pretty right and this needs lots of research and i would like to state a few points cause it would helps us for future projects.
And if you plan to make a video of somekind please contact us and we could help you prolote the video for such effort!

(Also have you noticed the lag on the site? Haha lol, we are well aware but there is not much we can do with 500 users all connected at the same time!)

**Comment by facundomedica** [comment]
@guillecro thought it was just my connection. Nice that you have that many users. What kind of infrastructure are we talking about?

**Comment by guillecro** [comment]
@facundomedica 
Thanks! For us is quite impressive :)
Ok, so virtuagora backend is basically PHP7 and the front-end uses modern Javascript frameworks server and client rendering. So the infrastructure is basically a LAMP stack. The idea of virtuagora was in the beginning to be a simple stack to be able to install in free hosting services.

We are using Apache2.4 right now (we didnt had time to prepare a nginx instance)
But even if we raise the amount of simultaneous clients, the number of current users still increases to higher numbers (obviously because of the closing date)

We do need an expert in server deployments for this jobs. Hopefully in the future we will post a job petition for this sutff.

**Comment by guillecro** [comment]
Ok. Back to the issue.

There is always a discussion with this kind of platforms.
Not only our objective is that people participate in different instances by voting, discussing, contributing and etc., but we also want people to take its time and understand the issue that the content is stating. 

Like. if you are going to contribute in a project, for a new law or something. Before doing anything, we want the people to really understand the purpose and **what are they voting or contributing**.

Of course this needs a lot of research when it comes to UI/UX cause these intentions are not compatible with nowadays assumptions, like for example:
- Users don't read more than XXX word
- Users don't spend XXX seconds in a content
- Users usually see 35% of a whole text

Well u know.. the average stats..
And this is a problem for participation platforms. Cause at the same time we need to understand the users objectives. For example, lets see the Ingenia case. We have the "Bancar" button on top of the content. Is it the best place? Maybe yes, but whats the real intention? To know about the project? To collaborate with ideas? Or just smash that button?

In this kind of platforms, sometimes the number doesnt mean anything. Maybe a project might get 500 likes but 3 comments might be even more important than those numbers.

About your suggestions, we will see what can we do. For example, you are right about the tooltip (actually you are right about everything) and we released as soon as we had it cause we had a deadline to accomplish. We want stuff to be well done but schedules sometimes make it harder.. I think you know how this goes, you are a developer like us, right?

In the next months we will launch a instance for Virtuagora, for the project, and we will submit questions and more topics related to the development of V2 (Version 2 is going to be builded with the participation of everybody, not only with an open repo, but with comments and suggestions too!)
